version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE=http://localhost:8000
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
